version: "3.4"

networks:
  pg:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:10.4
    build:
      context: .
      target: postgres-builder
    networks:
      - pg
    environment:
      - "POSTGRES_USER=hlluser"
      - "POSTGRES_PASSWORD=hllpassword"
